import { activeNetworkConfig } from "./config/networks";
import type { DashboardSnapshot } from "./lib/metaguildx";

const fallbackPackages = [10, 20, 40, 80, 160, 320, 640, 1280, 2560, 5120];
const fallbackBoxes = [1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0, 3.25];

export const fallbackSnapshot: DashboardSnapshot = {
  walletAddress: null,
  userId: null,
  sponsorId: null,
  joinedAt: null,
  packageLevel: null,
  isRebirthUser: false,
  totalContribution: "0",
  totalEarnings: "0",
  directReferrals: 0,
  totalTeamBusiness: "0",
  rebirthCount: 0,
  xCount: 0,
  internalWalletBalance: "0",
  currentPackageEscrow: "0",
  currentPackageBucketEarnings: "0",
  packageOneBucketEarnings: "0",
  withdrawablePlatformBalance: "0",
  withdrawableSettlementBalance: "0",
  externalWalletBalance: "0",
  connectedWalletValue: "0",
  connectedWalletAssets: [],
  connectedWalletAssetsError: null,
  connectedWalletHistory: [],
  connectedWalletHistoryError: null,
  connectedWalletHistoryCursor: null,
  settlementAssetLabel: "Settlement asset",
  settlementAssetAddress: null,
  pendingStakingReward: "0",
  stakingRewardPool: "0",
  totalStaked: "0",
  personalStaked: "0",
  stakeLockDurationLabel: "No active stake",
  stakeAutoCompound: false,
  stakePositions: [],
  cashbackPoolBalance: "0",
  totalTokenDistributed: "0",
  directIncome: "0",
  levelIncome: "0",
  spilloverIncome: "0",
  crossLineIncome: "0",
  cashbackIncome: "0",
  stakingIncome: "0",
  packagePrices: fallbackPackages,
  boxPrices: fallbackBoxes,
  rootUserId: null,
  isConnected: false,
  hasContractConfig: Boolean(activeNetworkConfig.contractAddress),
  isRegistered: false,
  featuredUsers: [],
  treePreview: [],
  activityFeed: [],
  spilloverHistory: [],
  networkBonusHistory: [],
  contractReady: false,
  contractWarning: null,
  directReferralIds: [],
  directReferralIncomeByUserId: {},
  rebirthIds: [],
  unlockedLevels: 0,
  unlockedLevelStatus: Array.from({ length: 10 }, () => false),
  leftBranchNodes: 0,
  rightBranchNodes: 0,
  leftBranchBusiness: "0",
  rightBranchBusiness: "0",
  levelTreeLeft: 0,
  levelTreeRight: 0,
  currentBoxId: 1,
  currentBoxPrice: "1.00",
  currentBoxDistributed: "0",
  currentBoxCap: "0",
  currentBoxRemaining: "0",
  mgxAllocated: "0",
  userActiveBoxId: null,
  pendingCashback: "0",
  isSurrendered: false,
  surrenderStatus: "Not available"
};
